sl-people-master/config/routes.rb
Rails.application.routes.draw do
  resources :people, only: :index do
    get :frequency, on: :collection
    get :possible_duplicates, on: :collection
  end
end

sl-people-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sl-people-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  # Protected: Decodes pagination info. This is only loaded by
  # controller actions that need it.
  def load_pagination
    @page = (params[:page].blank? ? 1 : params[:page].to_i)
    @per_page = 15
    if @page.negative?
      response = {
        errors: [I18n.t('errors.negative_page')]
      }
      render status: :bad_request, json: response
      return false
    end
  end
end

sl-people-master/app/controllers/concerns/near_duplicates.rb
module NearDuplicates
  extend ActiveSupport::Concern

  def detect_near_duplicates(list, percent)
    jarow = FuzzyStringMatch::JaroWinkler.create(:native)

    list.each_with_object({}) do |i1, r|
      dups = []
      list.each do |i2|
        next if i1 == i2

        distance = jarow.getDistance(i1, i2)

        if distance > percent
          dups << { distance: distance, value: i2 }
          r[i1] = dups
        end
      end
    end
  end
end

sl-people-master/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :load_api, only: [:index, :frequency, :possible_duplicates]
  before_action :load_pagination, only: [:index]

  include NearDuplicates

  def index
    response = @people_api.fetch(@page, @per_page)

    options = {
      data: response['data'],
      per_page: @per_page,
      current_page: response['metadata']['paging']['current_page'],
      total_count: response['metadata']['paging']['total_count']
    }

    @people = load_people(options).paginate(page: @page, per_page: @per_page)
  end

  def frequency
    # Loads all the People records into @people.
    # A helper method will calculate the frequencies for the view.
    load_all_people
  end

  def possible_duplicates
    # Detect near duplicates for email addresses
    # The greater the percent the better chance of a duplicate.
    load_all_people

    emails = @people.each_with_object([]) { |p, r| r << p['email_address'] }
    @possible_email_dups = detect_near_duplicates(emails, percent)
  end

  private

  def percent
    params[:percent].blank? ? 0.88 : params[:percent].to_f
  end

  def load_people(options)
    @people ||= (1..options[:total_count]).reduce([]) { |r, _i| r << {} }
    start = (options[:current_page] - 1) * options[:per_page]

    @people.slice!(start, options[:per_page])
    @people.insert(start, options[:data]).flatten!
  end

  def load_all_people
    per_page = 100 # max value for per_page
    response = @people_api.fetch(1, per_page)

    current_page = response['metadata']['paging']['current_page']
    total_pages = response['metadata']['paging']['total_pages']

    options = {
      data: response['data'],
      per_page: per_page,
      current_page: current_page,
      total_count: response['metadata']['paging']['total_count']
    }
    load_people(options)

    while options[:current_page] < total_pages
      options[:current_page] += 1
      response = @people_api.fetch(options[:current_page], per_page)
      options[:data] = response['data']
      load_people(options)
    end
  end

  def load_api
    @people_api = People::Api.new
  end
end

sl-people-master/app/helpers/application_helper.rb
module ApplicationHelper
end

sl-people-master/app/helpers/people_helper.rb
module PeopleHelper
  def email_frequencies(people)
    chars = Hash.new(0) # sets default value for any key to 0

    people.each do |p|
      str = p['email_address']
      chars = str.each_char.each_with_object(chars) do |char, result|
        result[char] += 1
      end
    end

    chars.sort_by { |_k, v| v }.reverse
  end

  def options_for_threshold(selected_value)
    selected = selected_value.blank? ? '0.88' : selected_value
    options = ['0.80', '0.85', '0.88', '0.90', '0.92', '0.93',
               '0.94', '0.95', '0.96', '0.97', '0.98', '0.99']
    options_for_select(options, selected)
  end
end

sl-people-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesLoftPeopleList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sl-people-master/app/views/people/frequency.html.haml
%div{style: 'margin-left: 20px;'}
  %h2 Frequency count of all the unique characters in all the email addresses from the people list API, sorted by frequency count.

  %br/

  = link_to 'Back to List of People', people_path, class: 'btn btn-primary'

  %br/

  %table.table.table-hover{style: 'width: 200px; margin-left: 20px;'}
    %thead
      %tr
        %th Character
        %th Count
    %tbody
      - email_frequencies(@people).each do |freq|
        %tr
          %td="#{freq[0]}"
          %td="#{freq[1]}"

sl-people-master/app/views/people/index.html.haml
%div.container
  .people.row
    %h2 List of People from SalesLoft API

  %br/

  .people.row
    = link_to 'Email Character Frequencies', frequency_people_path, class: 'btn btn-primary'

    = link_to 'Possible Duplicate People', possible_duplicates_people_path, class: 'btn btn-primary'

  %br/

  .people.content.row
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th Email Address
          %th Job Title
      %tbody
        - @people.each do |p|
          %tr
            %td="#{p['first_name']} #{p['last_name']}"
            %td="#{p['email_address']}"
            %td="#{p['title']}"

  = will_paginate @people, renderer: BootstrapPagination::Rails

sl-people-master/app/views/people/possible_duplicates.html.haml
:javascript
  function reload_list(percent) {
    val = percent.options[percent.selectedIndex].value;
    var url = location.toString().split('?')[0] + '?percent=' + val;
    location.assign(url);
  }

%div{style: 'margin-left: 20px;'}
  %h3 Shows a list of near duplicates for People.

  %br/

  = link_to 'Back to List of People', people_path, class: 'btn btn-primary'

  = select_tag :threshold, options_for_threshold(params[:threshold]), onchange: 'reload_list(this);'
  %span= 'Percent of duplicates '

  %br/

  %table{style: '500px; margin-left: 20px;'}
    %tr
      %td{style: 'vertical-align: top;'}
        %table.table.table-hover
          %thead
            %tr
              %th Email
              %th Possible duplicate
          %tbody
            - @possible_email_dups.keys.each do |email|
              %tr
                %td="#{email}"
                %td
                  - @possible_email_dups[email].each do |dups|
                    %span= dups[:value]
                    %span{style: 'color: #000000;'}= "(#{dups[:distance].round(4)})"
                    %br/